'use strict';
let x = 7;
console.log('The new value of x would be : +1 ');
console.log(x % 3);
let y = 28;
console.log('The new value of y would be : +1 ');
console.log(y % 3);
let z = 9.5;
console.log('The new value of z would be : 0.5 ');
console.log(z % 3);
let k = 2.5;
console.log('The new value of k would be : 2.5 ');
console.log(k % 3);
